name: pyinstaller-build
on: [push]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'src/ball_tracking.spec'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'PuttTracker.exe'
          options: --onefile, --name "Putt Tracker", --windowed, 